/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef com_linchaolong_apktoolplus_jiagu_utils_ApkToolPlus_h
#define com_linchaolong_apktoolplus_jiagu_utils_ApkToolPlus_h
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_linchaolong_apktoolplus_jiagu_utils_ApkToolPlus
 * Method:    encrypt
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_linchaolong_apktoolplus_jiagu_utils_ApkToolPlus_encrypt
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_linchaolong_apktoolplus_jiagu_utils_ApkToolPlus
 * Method:    decrypt
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_linchaolong_apktoolplus_jiagu_utils_ApkToolPlus_decrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
